### ISSUE TITLE
Novamente seus programas não possuem a opção de sair.

### ISSUE THREAD

**Issue by filipe0li** [Ismael66/Car_Storage#3]
![image](https://user-images.githubusercontent.com/76171152/146293758-3f9f507c-268f-42eb-894a-6fb603acda5c.png)

Por favor não use função recursiva sem necessidade.
Coloque em um do while e enquanto usuário não digitar a opção de sair ele continuara sendo executado.

**Comment by Ismael66** [comment]
Feito.

https://github.com/Ismael66/Car_Storage/blob/e8d112132f0dd3b9a6fcb7f6b3738a9db0a927ac/Domain/Model/Console_Carros.cs#L20
